import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { componentVariants, twMergeConfig } from "./component-variants";

/**
 * `dist/tokens.json` is generated by `pnpm nx build design-tokens`. Read from disk rather than
 * imported so this package needs no `resolveJsonModule` and ships no token payload at runtime.
 */
const TOKENS_PATH = join(
  dirname(fileURLToPath(import.meta.url)),
  "../../../design-tokens/dist/tokens.json"
);

function tokenNamesUnder(prefix: string): string[] {
  const tokens = JSON.parse(readFileSync(TOKENS_PATH, "utf8")) as Record<string, string>;
  return Object.keys(tokens)
    .filter((name) => name.startsWith(`${prefix}-`))
    .map((name) => name.slice(prefix.length + 1));
}

describe("twMergeConfig", () => {
  const themeScales = twMergeConfig.extend?.theme ?? {};

  it.each([
    ["font size", "text", themeScales.text],
    ["radius", "radius", themeScales.radius],
    ["shadow", "shadow", themeScales.shadow],
    ["easing", "ease", themeScales.ease],
    ["tracking", "tracking", themeScales.tracking],
    ["leading", "leading", themeScales.leading],
    ["font family", "font", themeScales.font],
  ])("declares every %s token emitted by design-tokens", (_label, prefix, declared) => {
    expect(new Set(declared as string[])).toEqual(new Set(tokenNamesUnder(prefix)));
  });

  it("declares the fractional spacing steps", () => {
    // Whole-number steps resolve through tailwind-merge's own number validator.
    const fractional = tokenNamesUnder("spacing").filter((name) => name.includes("-"));
    expect(new Set(themeScales.spacing as string[])).toEqual(new Set(fractional));
  });
});

describe("componentVariants", () => {
  it("keeps a font size and a text colour as separate decisions", () => {
    const heading = componentVariants({ base: "text-h1 text-text-muted" });
    expect(heading()).toContain("text-h1");
    expect(heading()).toContain("text-text-muted");
  });

  it("still overrides a font size with a later font size", () => {
    const size = componentVariants({ base: "text-body1", variants: { big: { true: "text-h2" } } });
    expect(size({ big: true })).toBe("text-h2");
  });

  it("overrides a shadow with a later shadow", () => {
    const shadow = componentVariants({
      base: "shadow-elevation1",
      variants: { raised: { true: "shadow-brand" } },
    });
    expect(shadow({ raised: true })).toBe("shadow-brand");
  });

  it("overrides a radius with a later radius", () => {
    const radius = componentVariants({
      base: "rounded-4",
      variants: { pill: { true: "rounded-6" } },
    });
    expect(radius({ pill: true })).toBe("rounded-6");
  });

  it("merges a caller className last", () => {
    const box = componentVariants({ base: "rounded-4 bg-surface-card" });
    expect(box({ className: "rounded-6" })).toBe("bg-surface-card rounded-6");
  });
});
