import StyleDictionary from "style-dictionary";

const kebab = (path) => path.map((p) => p.replace(/\./g, "-")).join("-");

StyleDictionary.registerFormat({
  name: "css/tailwind-theme",
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens.map((t) => `  --${kebab(t.path)}: ${t.$value ?? t.value};`);
    // `static` (not plain `@theme`) is required: Tailwind v4 tree-shakes any theme variable it
    // doesn't see referenced by a scanned utility class, which would silently drop tokens that
    // exist only for direct `var(--...)` consumption (custom CSS, JS style objects, Storybook
    // with no components yet) — defeating the point of a standalone design-tokens package.
    return `/* Generated by Style Dictionary — do not edit. Source: tokens/*.json */\n@theme static {\n${lines.join("\n")}\n}\n`;
  },
});

StyleDictionary.registerFormat({
  name: "typescript/tokens-const",
  format: ({ dictionary }) => {
    const entries = dictionary.allTokens
      .map((t) => `  "${kebab(t.path)}": "${t.$value ?? t.value}",`)
      .join("\n");
    return `/* Generated by Style Dictionary — do not edit. */\nexport const tokens = {\n${entries}\n} as const;\n\nexport type TokenName = keyof typeof tokens;\n`;
  },
});

// Deliberately NOT `transformGroup: "css"` / `"js"` (brief's example): both groups include a
// color value transform (`color/css` / `color/hex`) that pipes every color through tinycolor2,
// which lower-cases hex strings — e.g. `#EE2C68` -> `#ee2c68`. That breaks the literal-case
// contract (`--color-brand-primary: #EE2C68` in dist/theme.css) and mutates `$value` in place, so
// even the `t.$value ?? t.value` fallback in the custom formats above would see the lower-cased
// string. `attribute/cti` + `name/kebab` give every platform consistent kebab-case naming
// (`name/kebab` also prevents an SD "token collisions" warning that appears with `transforms: []`)
// without touching token values, so `$value` reaches every format exactly as authored.
const transforms = ["attribute/cti", "name/kebab"];

export default {
  source: ["tokens/**/*.json"],
  platforms: {
    css: {
      transforms,
      buildPath: "dist/",
      files: [{ destination: "theme.css", format: "css/tailwind-theme" }],
    },
    ts: {
      transforms,
      buildPath: "dist/",
      files: [{ destination: "tokens.ts", format: "typescript/tokens-const" }],
    },
    json: {
      transforms,
      buildPath: "dist/",
      files: [{ destination: "tokens.json", format: "json/flat" }],
    },
  },
};
